# Client listener
client:
  listen_ip: "0.0.0.0"
  listen_port: 20000

# Monitor listener
monitor:
  listen_ip: "0.0.0.0"
  listen_port: 8888
  token: "123"

# HTTP listener
http:
  listen_ip: "0.0.0.0"
  listen_port: 12345

# Log configuration
log:
  file_dir: "/home/dev1/talko/server/src/data/logs/"
  file_ame: "whisp_log"
  binary_package: false  # 0 转换为 false，1 为 true

# MySQL configuration
mysql:
  server_ip: "101.37.25.166"
  server_port: 3306
  user: "root"
  password: "123456"
  database: "flamingo"
